---
apiVersion: v1 
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.1
      ports: 
        - containerPort: 80
          name: nginx-port
          protocol: TCP
      resources: 
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
