---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins
spec:
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins:jdk11
      ports: 
        - containerPort: 8080
          name: http
          protocol: TCP